// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQXaNxPg1SlkIU_KMMBvFdUiZhahlOlE',
    appId: '1:831814189426:web:54dcee040d54d582829deb',
    messagingSenderId: '831814189426',
    projectId: 'flutterclass-movie-flutter-app',
    authDomain: 'flutterclass-movie-flutter-app.firebaseapp.com',
    storageBucket: 'flutterclass-movie-flutter-app.appspot.com',
    measurementId: 'G-87RC0CFG07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJ7ONzl631lf7pk53PQW-gVFRcWn4FYk',
    appId: '1:831814189426:android:0522bc14e79ce9d4829deb',
    messagingSenderId: '831814189426',
    projectId: 'flutterclass-movie-flutter-app',
    storageBucket: 'flutterclass-movie-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6h1d9FlJVHhMlASEMcbMOlVkZYrn4L1g',
    appId: '1:831814189426:ios:028e51641ae24e90829deb',
    messagingSenderId: '831814189426',
    projectId: 'flutterclass-movie-flutter-app',
    storageBucket: 'flutterclass-movie-flutter-app.appspot.com',
    iosClientId: '831814189426-v5upvcp577d6mvjhfjo3o6777s6fs78c.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTheatreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6h1d9FlJVHhMlASEMcbMOlVkZYrn4L1g',
    appId: '1:831814189426:ios:028e51641ae24e90829deb',
    messagingSenderId: '831814189426',
    projectId: 'flutterclass-movie-flutter-app',
    storageBucket: 'flutterclass-movie-flutter-app.appspot.com',
    iosClientId: '831814189426-v5upvcp577d6mvjhfjo3o6777s6fs78c.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTheatreApp',
  );
}
